version: "3.4"

services:
  wallet-checker:
    #image: wallet-checker:latest
    build:
      context: ../../../.
      dockerfile: ./script/docker/Dockerfile
    ports:
      - "8188:80"
    volumes:
      - ./proxies.txt:/app/proxies.txt
